export const HUGE_ARTISTS = new Set([
  "The Weeknd",
  "Taylor Swift",
  "Justin Bieber",
  "Ed Sheeran",
  "Ariana Grande",
  "Billie Eilish",
  "Drake",
  "Post Malone",
  "Bruno Mars",
  "Dua Lipa",
  "Olivia Rodrigo",
  "Travis Scott",
  "Kendrick Lamar",
  "Eminem",
  "Coldplay",
  "Imagine Dragons",
  "Maroon 5",
  "OneRepublic",
  "Harry Styles",
  "Shawn Mendes",
  "Adele",
  "SZA",
  "Doja Cat",
  "Charlie Puth",
  "Khalid",
  "BTS",
  "BLACKPINK",

  "Arijit Singh",
  "Atif Aslam",
  "Pritam",
  "A.R. Rahman",
  "Armaan Malik",
  "Jubin Nautiyal",
  "Shreya Ghoshal",
  "Sonu Nigam",
  "Diljit Dosanjh",
  "Sid Sriram",
  "Anirudh Ravichander",
  "Vishal Mishra",
  "Darshan Raval",
  "King",
  "Anuv Jain",
  "AP Dhillon",
  "Shubh",
  "Sidhu Moose Wala",
  "Joji",
  "Michael Jackson",
  "Elvis Presley",
  "Queen",
  "The Beatles",
  "Led Zeppelin",
  "Pink Floyd",
  "Nirvana",
  "AC/DC",
  "Guns N' Roses",
  "Metallica",
  "Linkin Park",
  "Red Hot Chili Peppers",
  "The Rolling Stones",
  "U2",
  "Coldplay",
  "Radiohead",
  "Foo Fighters",
  "Green Day",
  "The Who",
  "Pearl Jam",
  "The Doors",
  "The Clash",
  "The Police",
  "Fleetwood Mac",
  "The Eagles",
  "Mac DeMarco",
  "Tame Impala",
  "Arctic Monkeys",
  "The Strokes",
  "Vampire Weekend",
]);